apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- egress-kafka-mqtt-to-badge.yaml
namespace: cackalacky
images:
- name: 059039070213.dkr.ecr.us-east-1.amazonaws.com/cackalacky/2025/cyberpartner/svc-egress-mqtt-to-badge
  newName: 059039070213.dkr.ecr.us-east-1.amazonaws.com/cackalacky/2025/cyberpartner/svc-egress-mqtt-to-badge
  newTag: main-260cb9664fe3a2f728810280638592732f33393c
